version: '3.8'

services:
  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: calcupedev_proxy
    ports:
      - "8080:80"
    depends_on:
      - portal
      - api_epi
      - api_stat
      - api_sample
    networks:
      - calcupedev_net
    restart: unless-stopped

  # ----------------------------------------------------------------------------
  # 2. Portal Web (Frontend Central Vite/React o HTML srv)
  # ----------------------------------------------------------------------------
  portal:
    build:
      context: ./portal
      dockerfile: Dockerfile
    container_name: calcupedev_portal
    networks:
      - calcupedev_net
    restart: unless-stopped

  # ----------------------------------------------------------------------------
  # 3. Micro-servicio: Epidemiología (R-Shiny)
  # ----------------------------------------------------------------------------
  api_epi:
    build:
      context: ./api_epi
      dockerfile: Dockerfile
    container_name: calcupedev_api_epi
    networks:
      - calcupedev_net
    restart: unless-stopped

  # ----------------------------------------------------------------------------
  # 4. Micro-servicio: Estadística (R-Shiny)
  # ----------------------------------------------------------------------------
  api_stat:
    build:
      context: ./api_stat
      dockerfile: Dockerfile
    container_name: calcupedev_api_stat
    networks:
      - calcupedev_net
    restart: unless-stopped

  # ----------------------------------------------------------------------------
  # 5. Micro-servicio: Tamaño Muestral (R-Shiny)
  # ----------------------------------------------------------------------------
  api_sample:
    build:
      context: ./api_sample
      dockerfile: Dockerfile
    container_name: calcupedev_api_sample
    networks:
      - calcupedev_net
    restart: unless-stopped

networks:
  calcupedev_net:
    driver: bridge
